name: Build & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies # Install all deps
        run: yarn

      - name: Sync versions # Sync versions
        run: yarn syncprojects

      - name: Run tests
        run: yarn test --code-coverage --configuration=ci

      # - name: Upload coverage reports
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     fail_ci_if_error: true
      #     verbose: false
      #     dry_run: false

      # # Demo Build for GitHub Pages 
      # - name: Build demo app # Build Schematics and move
      #   run: yarn build:demo --base-href https://MSubhan01.github.io/ngx-clamp/

      - name: Build ngx-clamp # Build
        run: yarn build

      - name: Publish NPM
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
        run: npm publish --folder dist/ngx-clamp
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}

      - name: Publish NPM BETA
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == true
        run: npm publish --folder dist/ngx-clamp --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}

      # # Publish to GitHub Package Registry
      # - name: Set up package for GPR
      #   if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
      #   run: yarn gpr:setup

      # - name: Use GPR
      #   if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
      #   uses: actions/setup-node@main
      #   with:
      #     node-version: 14
      #     registry-url: https://npm.pkg.github.com/
      #     scope: '@MSubhan01'

      # - name: Publish to GitHub Package Registry
      #   if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
      #   run: |
      #     cd dist/ngx-clamp
      #     npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{github.token}}

      # # Need Environment Variables
      # - name: Deploy Github Pages
      #   if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'beta') == false
      #   uses: peaceiris/actions-gh-pages@v2.5.0
      #   env:
      #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: ./dist/demo
