name: Release npm package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Setup
        run: npm ci
      # - run: npm test
      - name: Build
        run: npm run build --if-present
      # - run: cd ./dist/ngx-clamp
      # - run: npm publish
      # - run: npx semantic-release
      - name: Publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TKN }}
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}